// Writes android/app/src/main/res/values/firebase_values.xml from
// android/app/google-services.json — what Google's Gradle plugin would
// generate (it may not support this project's newer Android Gradle Plugin).
// None of these values are secret. Rerun after replacing google-services.json:
//   node tool/gen_firebase_values.mjs
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
const g = JSON.parse(readFileSync('android/app/google-services.json', 'utf8'));
const pkg = 'com.almuntahha.sidra_lms';
const c = g.client.find((x) => x.client_info.android_client_info.package_name === pkg);
if (!c) throw new Error(`google-services.json has no app ${pkg}`);
const v = {
  google_app_id: c.client_info.mobilesdk_app_id,
  gcm_defaultSenderId: g.project_info.project_number,
  google_api_key: c.api_key[0].current_key,
  google_crash_reporting_api_key: c.api_key[0].current_key,
  project_id: g.project_info.project_id,
  google_storage_bucket: g.project_info.storage_bucket,
};
mkdirSync('android/app/src/main/res/values', { recursive: true });
writeFileSync('android/app/src/main/res/values/firebase_values.xml',
  '<?xml version="1.0" encoding="utf-8"?>\n<!-- Generated by tool/gen_firebase_values.mjs from google-services.json. -->\n' +
  '<resources xmlns:tools="http://schemas.android.com/tools" tools:keep="@string/*">\n' +
  Object.entries(v).filter(([, x]) => x).map(([k, x]) =>
    `    <string name="${k}" translatable="false">${x}</string>`).join('\n') + '\n</resources>\n');
console.log('firebase_values.xml written for', v.project_id);
